#!/bin/bash

# Debian 12 System Tuning for qBittorrent Maximum Performance
# Optimizes kernel parameters, file descriptors, network stack, and I/O for high-performance torrent handling

set -o pipefail

# Must run as root
if [[ ${EUID} -ne 0 ]]; then
	printf '%s\n' "ERROR: This script must be run as root"
	printf '%s\n' "Usage: sudo $0"
	exit 1
fi

# Color codes
readonly color_green='\033[0;32m'
readonly color_yellow='\033[0;33m'
readonly color_blue='\033[0;34m'
readonly color_cyan='\033[0;36m'
readonly color_end='\033[0m'

# Configuration
readonly SYSCTL_CONF="/etc/sysctl.d/99-qbittorrent-performance.conf"
readonly LIMITS_CONF="/etc/security/limits.d/qbittorrent.conf"
readonly SYSTEMD_CONF="/etc/systemd/system/qbittorrent-nox.service.d/performance.conf"
readonly UDEV_NVME="/etc/udev/rules.d/60-nvme-scheduler.rules"
readonly CPU_GOV_SERVICE="/etc/systemd/system/cpu-performance.service"

# Backup directory
readonly BACKUP_DIR="/root/qbt-tune-backup-$(date +%Y%m%d_%H%M%S)"

_print() {
	local level="${1}"
	local message="${2}"

	case "${level}" in
		INFO) printf '%b[INFO]%b %s\n' "${color_blue}" "${color_end}" "${message}" ;;
		SUCCESS) printf '%b[✓]%b %s\n' "${color_green}" "${color_end}" "${message}" ;;
		WARNING) printf '%b[!]%b %s\n' "${color_yellow}" "${color_end}" "${message}" ;;
		SECTION) printf '\n%b=== %s ===%b\n' "${color_cyan}" "${message}" "${color_end}" ;;
	esac
}

_backup_file() {
	local file="${1}"
	if [[ -f ${file} ]]; then
		mkdir -p "${BACKUP_DIR}"
		cp -a "${file}" "${BACKUP_DIR}/"
		_print INFO "Backed up: ${file}"
	fi
}

# Detect hardware
_detect_hardware() {
	_print SECTION "Detecting Hardware"

	# CPU cores
	CPU_CORES=$(nproc)
	_print INFO "CPU cores: ${CPU_CORES}"

	# Check for AMD EPYC
	if grep -q "EPYC" /proc/cpuinfo; then
		IS_EPYC=1
		EPYC_MODEL=$(grep -m1 "model name" /proc/cpuinfo | cut -d: -f2 | xargs)
		_print SUCCESS "AMD EPYC detected: ${EPYC_MODEL}"
	else
		IS_EPYC=0
		_print INFO "Non-EPYC CPU detected"
	fi

	# Memory
	TOTAL_MEM_GB=$(free -g | awk '/^Mem:/ {print $2}')
	_print INFO "Total memory: ${TOTAL_MEM_GB} GB"

	# Detect NVMe
	if ls /dev/nvme* &>/dev/null; then
		HAS_NVME=1
		NVME_DEVICES=$(ls /dev/nvme*n* 2>/dev/null | grep -v 'p[0-9]' | tr '\n' ' ')
		_print SUCCESS "NVMe detected: ${NVME_DEVICES}"
	else
		HAS_NVME=0
		_print INFO "No NVMe devices detected"
	fi

	# Network interfaces
	NET_SPEED=$(ethtool "$(ip route | grep default | awk '{print $5}' | head -1)" 2>/dev/null | awk '/Speed:/ {print $2}')
	_print INFO "Network speed: ${NET_SPEED:-Unknown}"
}

# Tune kernel parameters
_tune_sysctl() {
	_print SECTION "Configuring Kernel Parameters"

	_backup_file "${SYSCTL_CONF}"

	cat > "${SYSCTL_CONF}" << 'EOF'
# qBittorrent Performance Tuning - Kernel Parameters
# Generated by debian12-tune.bash

# === Network Performance ===

# TCP buffer sizes (min, default, max)
net.ipv4.tcp_rmem = 4096 87380 268435456
net.ipv4.tcp_wmem = 4096 65536 268435456

# Maximum socket buffer sizes
net.core.rmem_max = 536870912
net.core.wmem_max = 536870912

# Increase default buffer sizes
net.core.rmem_default = 16777216
net.core.wmem_default = 16777216

# Network device backlog
net.core.netdev_max_backlog = 50000

# SYN backlog
net.ipv4.tcp_max_syn_backlog = 30000

# Connection backlog
net.core.somaxconn = 8192

# TCP optimization
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_intvl = 15

# Fast socket recycling
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_window_scaling = 1

# SYN cookies for DDoS protection
net.ipv4.tcp_syncookies = 1

# Increase local port range
net.ipv4.ip_local_port_range = 10000 65535

# Connection tracking
net.netfilter.nf_conntrack_max = 1048576
net.netfilter.nf_conntrack_tcp_timeout_established = 600
net.netfilter.nf_conntrack_tcp_timeout_time_wait = 30

# === File System ===

# Maximum file handles
fs.file-max = 10485760

# Inotify watches
fs.inotify.max_user_watches = 2097152
fs.inotify.max_user_instances = 8192
fs.inotify.max_queued_events = 32768

# Async I/O
fs.aio-max-nr = 1048576

# === Virtual Memory ===

# Swappiness (prefer RAM)
vm.swappiness = 1

# Dirty page writeback
vm.dirty_ratio = 10
vm.dirty_background_ratio = 5

# Cache pressure
vm.vfs_cache_pressure = 50

# Overcommit
vm.overcommit_memory = 1

# Huge pages (for high RAM systems)
vm.nr_hugepages = 2048

# === Kernel ===

# Increase PID limit
kernel.pid_max = 4194304

# Core dump handling
kernel.core_pattern = /tmp/core-%e-%p-%t

# Panic on OOM (optional, for production)
# vm.panic_on_oom = 1

EOF

	# Add EPYC-specific tuning
	if [[ ${IS_EPYC} -eq 1 ]]; then
		cat >> "${SYSCTL_CONF}" << 'EOF'

# === EPYC-Specific Optimizations ===

# NUMA balancing
kernel.numa_balancing = 0

# Disable transparent huge pages defrag (better for EPYC)
# (Set via /sys/kernel/mm/transparent_hugepage/defrag)

EOF
	fi

	# Add high-memory tuning
	if [[ ${TOTAL_MEM_GB} -ge 64 ]]; then
		cat >> "${SYSCTL_CONF}" << 'EOF'

# === High-RAM Optimizations (64GB+) ===

# More aggressive caching
vm.vfs_cache_pressure = 30
vm.min_free_kbytes = 1048576

EOF
	fi

	sysctl -p "${SYSCTL_CONF}" > /dev/null 2>&1
	_print SUCCESS "Kernel parameters configured: ${SYSCTL_CONF}"
}

# Configure file descriptor limits
_tune_limits() {
	_print SECTION "Configuring File Descriptor Limits"

	_backup_file "${LIMITS_CONF}"

	cat > "${LIMITS_CONF}" << 'EOF'
# qBittorrent file descriptor limits
# For user running qBittorrent

*               soft    nofile          10485760
*               hard    nofile          10485760
*               soft    nproc           65536
*               hard    nproc           65536
root            soft    nofile          10485760
root            hard    nofile          10485760

EOF

	_print SUCCESS "File descriptor limits configured: ${LIMITS_CONF}"
	_print WARNING "Users need to re-login for limits to take effect"
}

# NVMe optimization
_tune_nvme() {
	if [[ ${HAS_NVME} -eq 0 ]]; then
		_print INFO "Skipping NVMe tuning (no NVMe detected)"
		return
	fi

	_print SECTION "Optimizing NVMe Devices"

	# Create udev rule for NVMe scheduler
	cat > "${UDEV_NVME}" << 'EOF'
# Set NVMe I/O scheduler to 'none' for maximum performance
ACTION=="add|change", KERNEL=="nvme[0-9]n[0-9]", ATTR{queue/scheduler}="none", ATTR{queue/nr_requests}="1024", ATTR{queue/read_ahead_kb}="512"

EOF

	_print SUCCESS "NVMe udev rules created: ${UDEV_NVME}"

	# Apply immediately
	for dev in ${NVME_DEVICES}; do
		dev_name=$(basename "${dev}")
		printf 'none' > "/sys/block/${dev_name}/queue/scheduler" 2>/dev/null || true
		printf '1024' > "/sys/block/${dev_name}/queue/nr_requests" 2>/dev/null || true
		printf '512' > "/sys/block/${dev_name}/queue/read_ahead_kb" 2>/dev/null || true
		_print INFO "Optimized: ${dev}"
	done

	udevadm control --reload-rules
	_print SUCCESS "NVMe optimizations applied"
}

# CPU governor optimization
_tune_cpu_governor() {
	_print SECTION "Configuring CPU Governor"

	if [[ ! -d /sys/devices/system/cpu/cpu0/cpufreq ]]; then
		_print WARNING "CPU frequency scaling not available"
		return
	fi

	# Create systemd service for performance governor
	mkdir -p "$(dirname "${CPU_GOV_SERVICE}")"

	cat > "${CPU_GOV_SERVICE}" << 'EOF'
[Unit]
Description=Set CPU governor to performance for qBittorrent
After=multi-user.target

[Service]
Type=oneshot
ExecStart=/bin/bash -c 'for gov in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo performance > $gov 2>/dev/null || true; done'
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

EOF

	systemctl daemon-reload
	systemctl enable cpu-performance.service
	systemctl start cpu-performance.service

	_print SUCCESS "CPU governor set to performance"
}

# SystemD service optimization
_tune_systemd_service() {
	_print SECTION "Configuring SystemD Service Limits"

	mkdir -p "$(dirname "${SYSTEMD_CONF}")"

	cat > "${SYSTEMD_CONF}" << EOF
# qBittorrent-nox performance overrides
[Service]

# File descriptors
LimitNOFILE=10485760

# Processes
LimitNPROC=65536

# Core dumps
LimitCORE=infinity

# Memory locking
LimitMEMLOCK=infinity

# CPU affinity (all cores)
CPUAffinity=0-$((CPU_CORES-1))

# Nice level (priority)
Nice=-5

# I/O scheduling class (best-effort, high priority)
IOSchedulingClass=2
IOSchedulingPriority=0

EOF

	# Add NUMA pinning for EPYC
	if [[ ${IS_EPYC} -eq 1 ]] && command -v numactl &>/dev/null; then
		cat >> "${SYSTEMD_CONF}" << 'EOF'

# NUMA optimization
ExecStart=
ExecStart=/usr/bin/numactl --localalloc /usr/local/bin/qbittorrent-nox

EOF
	fi

	systemctl daemon-reload
	_print SUCCESS "SystemD service limits configured: ${SYSTEMD_CONF}"
	_print WARNING "Restart qBittorrent-nox service to apply changes"
}

# Network interface tuning
_tune_network() {
	_print SECTION "Optimizing Network Interfaces"

	local primary_if=$(ip route | grep default | awk '{print $5}' | head -1)

	if [[ -z ${primary_if} ]]; then
		_print WARNING "Could not detect primary network interface"
		return
	fi

	# Increase ring buffer sizes
	ethtool -G "${primary_if}" rx 4096 tx 4096 2>/dev/null || _print INFO "Ring buffer size unchanged"

	# Enable offloading features
	ethtool -K "${primary_if}" tso on gso on gro on 2>/dev/null || _print INFO "Offloading features unchanged"

	# Disable hardware interrupt coalescing for low latency
	ethtool -C "${primary_if}" rx-usecs 0 tx-usecs 0 2>/dev/null || _print INFO "Interrupt coalescing unchanged"

	_print SUCCESS "Network interface optimized: ${primary_if}"
}

# IRQ affinity (spread interrupts across CPUs)
_tune_irq_affinity() {
	_print SECTION "Configuring IRQ Affinity"

	if [[ ${CPU_CORES} -lt 8 ]]; then
		_print INFO "Skipping IRQ affinity (CPU cores < 8)"
		return
	fi

	# Install irqbalance if not present
	if ! command -v irqbalance &>/dev/null; then
		apt-get install -y irqbalance > /dev/null 2>&1
		_print INFO "Installed irqbalance"
	fi

	# Configure irqbalance for performance
	sed -i 's/#IRQBALANCE_BANNED_CPUS=/IRQBALANCE_BANNED_CPUS=/' /etc/default/irqbalance
	systemctl enable irqbalance
	systemctl restart irqbalance

	_print SUCCESS "IRQ balancing enabled"
}

# Disable unnecessary services
_disable_unnecessary_services() {
	_print SECTION "Optimizing System Services"

	local services_to_disable=(
		"bluetooth.service"
		"cups.service"
		"avahi-daemon.service"
		"ModemManager.service"
	)

	for service in "${services_to_disable[@]}"; do
		if systemctl is-enabled "${service}" &>/dev/null; then
			systemctl disable "${service}" 2>/dev/null || true
			systemctl stop "${service}" 2>/dev/null || true
			_print INFO "Disabled: ${service}"
		fi
	done

	_print SUCCESS "Unnecessary services disabled"
}

# Generate summary report
_generate_summary() {
	_print SECTION "Tuning Summary"

	local summary="/root/qbt-tune-summary.txt"

	{
		printf 'Debian 12 qBittorrent Tuning Summary\n'
		printf '=====================================\n\n'
		printf 'Date: %s\n\n' "$(date)"

		printf 'Hardware Detected:\n'
		printf '  CPU Cores: %s\n' "${CPU_CORES}"
		printf '  Memory: %s GB\n' "${TOTAL_MEM_GB}"
		printf '  EPYC: %s\n' "$([[ ${IS_EPYC} -eq 1 ]] && echo 'Yes' || echo 'No')"
		printf '  NVMe: %s\n' "$([[ ${HAS_NVME} -eq 1 ]] && echo 'Yes' || echo 'No')"
		printf '\n'

		printf 'Applied Optimizations:\n'
		printf '  ✓ Kernel parameters (sysctl)\n'
		printf '  ✓ File descriptor limits\n'
		[[ ${HAS_NVME} -eq 1 ]] && printf '  ✓ NVMe I/O scheduler\n'
		printf '  ✓ CPU governor (performance)\n'
		printf '  ✓ SystemD service limits\n'
		printf '  ✓ Network interface tuning\n'
		printf '  ✓ IRQ balancing\n'
		printf '\n'

		printf 'Configuration Files:\n'
		printf '  - %s\n' "${SYSCTL_CONF}"
		printf '  - %s\n' "${LIMITS_CONF}"
		printf '  - %s\n' "${SYSTEMD_CONF}"
		[[ ${HAS_NVME} -eq 1 ]] && printf '  - %s\n' "${UDEV_NVME}"
		printf '  - %s\n' "${CPU_GOV_SERVICE}"
		printf '\n'

		printf 'Backup Location:\n'
		printf '  %s\n' "${BACKUP_DIR}"
		printf '\n'

		printf 'Next Steps:\n'
		printf '  1. Reboot system for all changes to take effect\n'
		printf '  2. Re-login for file descriptor limits\n'
		printf '  3. Restart qBittorrent-nox service\n'
		printf '  4. Run performance tests: ./qbt-performance-test.bash\n'
		printf '\n'

		printf 'Verification Commands:\n'
		printf '  sysctl -a | grep -E "(tcp_rmem|file-max|vm.swappiness)"\n'
		printf '  ulimit -n\n'
		printf '  cat /sys/block/nvme0n1/queue/scheduler\n'
		printf '  cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor\n'
		printf '  systemctl status qbittorrent-nox\n'

	} | tee "${summary}"

	_print SUCCESS "Summary saved to: ${summary}"
}

# Main execution
main() {
	printf '%b\n' "${color_cyan}"
	printf '╔═══════════════════════════════════════════════════════════╗\n'
	printf '║  Debian 12 qBittorrent Performance Tuning Script         ║\n'
	printf '║  Optimizes kernel, I/O, network for maximum performance  ║\n'
	printf '╚═══════════════════════════════════════════════════════════╝\n'
	printf '%b\n' "${color_end}"

	# Check Debian version
	if [[ ! -f /etc/debian_version ]]; then
		_print WARNING "Not running Debian"
	fi

	_detect_hardware
	_tune_sysctl
	_tune_limits
	_tune_nvme
	_tune_cpu_governor
	_tune_systemd_service
	_tune_network
	_tune_irq_affinity
	_disable_unnecessary_services
	_generate_summary

	printf '\n%b' "${color_green}"
	printf '╔═══════════════════════════════════════════════════════════╗\n'
	printf '║              ✓ System Tuning Complete!                   ║\n'
	printf '║                                                           ║\n'
	printf '║  Please REBOOT for all optimizations to take effect     ║\n'
	printf '╚═══════════════════════════════════════════════════════════╝\n'
	printf '%b\n' "${color_end}"
}

main
