# @credits https://github.com/c0re100/qBittorrent-Enhanced-Edition
name: matrix multi build and release - artifacts

on:
  workflow_dispatch:

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq -y

      - name: Download Assessts
        run: |
          mapfile -t assets < <(curl -sL "https://api.github.com/repos/userdocs/qbt-workflow-files/releases/latest" | jq -r ".assets | .[].browser_download_url")
          for urls in "${assets[@]}"; do
              curl -sLO "${urls}"
          done

      - uses: actions/upload-artifact@v3
        with:
          path: "*.tar.xz"

  build:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os_id: [alpine]
        os_version_id: [edge]
        arch_type: [x86_64, armhf, armv7, aarch64]
        libtorrent_version: ["1.2", "2.0"]
        build_tool: ["", cmake]
        include:
          - build_tool: ""
            qbt_qt_version_name: "qt5-"
            qbt_qt_version: "5"

          - build_tool: "cmake"
            qbt_qt_version_name: ""
            qbt_qt_version: "6"

          - libtorrent_version: "2.0"
            preview_release: false

          - libtorrent_version: "1.2"
            preview_release: true

    name: "${{ matrix.arch_type }}-${{ matrix.qbt_qt_version_name }}libtorrent-v${{ matrix.libtorrent_version }}"

    env:
      build_dir: "qbt-build"
      name: "${{ matrix.arch_type }}-${{ matrix.qbt_qt_version_name }}libtorrent-v${{ matrix.libtorrent_version }}"

    steps:
      - uses: actions/checkout@v3

      - name: Host - create build dir
        run: mkdir -p ${{ env.build_dir }}

      - name: Host - Download all artifact
        uses: actions/download-artifact@v3

      - name: Host - organise libtorrent files
        run: |

          libtorrent_1_2_github_tag="$(git ls-remote -q -t --refs "https://github.com/arvidn/libtorrent.git" | awk '/\/v1/{sub("refs/tags/", "");sub("(.*)(-[^0-9].*)(.*)", ""); print $2 }' | awk '!/^$/' | sort -rV | head -n1)"
          libtorrent_2_0_github_tag="$(git ls-remote -q -t --refs "https://github.com/arvidn/libtorrent.git" | awk '/\/v2/{sub("refs/tags/", "");sub("(.*)(-[^0-9].*)(.*)", ""); print $2 }' | awk '!/^$/' | sort -rV | head -n1)"

          if [[ "${{ matrix.libtorrent_version }}" =~ ^1\.2 ]]; then
              mv -f artifact/libtorrent.${libtorrent_1_2_github_tag/v/}.tar.xz artifact/libtorrent.tar.xz
              rm -f artifact/libtorrent.${libtorrent_2_0_github_tag/v/}.tar.xz
          fi

          if [[ "${{ matrix.libtorrent_version }}" =~ ^2\.0 ]]; then
              mv -f artifact/libtorrent.${libtorrent_2_0_github_tag/v/}.tar.xz artifact/libtorrent.tar.xz
              rm -f artifact/libtorrent.${libtorrent_1_2_github_tag/v/}.tar.xz
          fi

      - name: Host - organise qt files
        run: |
          if [[ "${{ matrix.qbt_qt_version }}" =~ ^5 ]]; then
              mv -f artifact/qt5base.tar.xz artifact/qtbase.tar.xz
              mv -f artifact/qt5tools.tar.xz artifact/qttools.tar.xz
              rm -f artifact/qt6base.tar.xz artifact/qt6tools.tar.xz
          fi

          if [[ "${{ matrix.qbt_qt_version }}" =~ ^6 ]]; then
              mv -f artifact/qt6base.tar.xz artifact/qtbase.tar.xz
              mv -f artifact/qt6tools.tar.xz artifact/qttools.tar.xz
              rm -f artifact/qt5base.tar.xz artifact/qt5tools.tar.xz
          fi

      - name: Host - Move organised artifacts to ${{ env.build_dir }}
        run: mv -f artifact/* ${{ env.build_dir }}

      - name: Host - Display structure of downloaded artifcats workspace
        run: ls -R

      - name: Host - update
        run: sudo apt-get update

      - name: Host - upgrade
        run: sudo apt-get -y upgrade

      - name: Host - Install host qemu-static
        run: sudo apt-get install -y qemu binfmt-support qemu-user-static

      - name: Host - Docker multiarch bootstrap
        run: sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Host - Create Docker template env file
        run: |
          echo "qbt_build_tool=${{ matrix.build_tool }}" > env.custom
          echo "qbt_cross_name=${{ matrix.arch_type  }}" >> env.custom
          echo "qbt_libtorrent_version=${{ matrix.libtorrent_version }}" >> env.custom
          echo "qbt_qt_version=${{ matrix.qbt_qt_version }}" >> env.custom
          echo "qbt_workflow_artifacts=yes" >> env.custom

      - name: Host - Create docker multiarch container
        run: docker run --name multiarch -it -d --env-file env.custom -w /root -v ${{ github.workspace }}:/root ${{ matrix.os_id }}:${{ matrix.os_version_id }}

      - name: Docker - apk update
        run: docker exec -w /root multiarch apk update

      - name: Docker - apk install bash
        run: docker exec -w /root multiarch apk add bash

      - name: Docker - Bootstrap
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh -bs-a

      - name: Host - Bootstrap release tag
        run: echo "release_tag=$(cat ${{ env.build_dir }}/release_info/tag.md)" >> $GITHUB_ENV

      - name: Host - Bootstrap release title
        run: echo "release_title=$(cat ${{ env.build_dir }}/release_info/title.md)" >> $GITHUB_ENV

      - name: Docker - zlib-ng
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh zlib

      - name: Docker - iconv
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh iconv

      - name: Docker - icu
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh icu

      - name: Docker - openssl
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh openssl

      - name: Docker - boost
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh boost

      - name: Docker - libtorrent
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh libtorrent

      - name: Docker - double_conversion
        if: matrix.build_tool == 'cmake'
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh double_conversion

      - name: Docker - qtbase -i
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh qtbase -i

      - name: Docker - qttools
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh qttools

      - name: Docker - qbittorrent
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh qbittorrent

      - name: Docker - "Set release asset name"
        run: docker exec -w /root/${{ env.build_dir }}/completed multiarch mv -f qbittorrent-nox ${{ matrix.arch_type }}-${{ matrix.qbt_qt_version_name }}qbittorrent-nox

      - name: Host- Create release - tag - assets
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: "${{ matrix.preview_release }}"
          artifacts: "${{ env.build_dir }}/completed/${{ matrix.arch_type }}-${{ matrix.qbt_qt_version_name }}qbittorrent-nox,${{ env.build_dir }}/release_info/dependency-version.json"
          replacesArtifacts: true
          tag: "${{ env.release_tag }}"
          name: "${{ env.release_title }}"
          bodyFile: "${{ env.build_dir }}/release_info/release.md"
          allowUpdates: true
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Archive code coverage results
        if: matrix.build_tool == 'cmake'
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.name }}-graphs"
          path: "${{ env.build_dir }}/completed/*.png"
